sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: ciel-hive
name: ciel-hive
description: 今天你对我爱答不理，明天我让你高攀不起=_=

github: https://github.com/Ciel-hive
email: 1352447939@qq.com
rss: true

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
 
theme: jekyll-theme-minimalism