sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: ciel-hive
name: ciel-hive
description: Stay Hungry, Stay Foolish

github: https://ciel-hive.github.io
email: mailto:1352447939@qq.com
rss: false

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
 
theme: jekyll-theme-minimalism